In [4]:
import numpy as np

def question_1():
    """
    What is a Python library? Why do we use Python libraries?
    """
    print("A Python library is a collection of functions and methods that allow you to perform many actions without writing your own code.")
    print("Libraries in Python provide pre-written functionalities to perform tasks, such as mathematical operations, data manipulation, and more.")
    print("We use Python libraries to save time and effort by leveraging the work that others have already done, allowing us to focus on solving specific problems.")

def question_2():
    """
    What is the difference between a Numpy array and a List?
    """
    print("Numpy arrays are homogeneous collections of elements with a fixed size, whereas lists in Python can contain elements of different data types and sizes.")
    print("Numpy arrays offer more efficient storage and operations for numerical data, especially for large datasets and mathematical computations.")

def question_3():
    """
    Find the shape, size, and dimension of the following array
    """
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    shape = arr.shape
    size = arr.size
    dimension = arr.ndim
    print("Shape:", shape)
    print("Size:", size)
    print("Dimension:", dimension)

def question_4():
    """
    Write Python code to access the first row of the following array
    """
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    first_row = arr[0]
    print("First Row:", first_row)

def question_5():
    """
    How do you access the element at the third row and fourth column from the given numpy array?
    """
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    element = arr[2, 3]
    print("Element at third row and fourth column:", element)

def question_6():
    """
    Write code to extract all odd-indexed elements from the given numpy array
    """
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    odd_indexed_elements = arr[::2, ::2]
    print("Odd-indexed elements:", odd_indexed_elements)

def question_7():
    """
    How can you generate a random 3x3 matrix with values between 0 and 1?
    """
    random_matrix = np.random.rand(3, 3)
    print("Random 3x3 matrix with values between 0 and 1:")
    print(random_matrix)

def question_8():
    """
    Describe the difference between np.random.rand and np.random.randn
    """
    print("np.random.rand generates random numbers from a uniform distribution between 0 and 1.")
    print("np.random.randn generates random numbers from a standard normal distribution (mean=0, variance=1).")

def question_9():
    """
    Write code to increase the dimension of the following array
    """
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    increased_dimension_arr = arr[np.newaxis, :]
    print("Array with increased dimension:")
    print(increased_dimension_arr)

def question_10():
    """
    How to transpose the following array in NumPy?
    """
    arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    transposed_arr = np.transpose(arr)
    print("Transposed array:")
    print(transposed_arr)

def question_11():


    matrix_A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    matrix_B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

    # Index-wise multiplication
    index_wise_multiplication = matrix_A2 * matrix_B2
    print("Index-wise multiplication:")
    print(index_wise_multiplication)

    # Matrix multiplication (dot product)
    # Note: In matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix.
    # In this case, matrix_A2 has shape (3, 4) and matrix_B2 has shape (3, 4), which are not aligned for multiplication.
    # To perform matrix multiplication, we need to transpose matrix_B2 to make the shapes compatible.
    matrix_multiplication = np.dot(matrix_A2, matrix_B2.T)  # Transpose matrix_B2
    print("Matrix multiplication:")
    print(matrix_multiplication)

    # Addition of both matrices
    matrix_addition = matrix_A2 + matrix_B2
    print("Addition of matrices:")
    print(matrix_addition)

    # Subtraction of matrix B from matrix A
    matrix_subtraction = matrix_A2 - matrix_B2
    print("Subtraction of matrix B from matrix A:")
    print(matrix_subtraction)

    # Division of matrix B by A
    matrix_division = np.divide(matrix_B2, matrix_A2)
    print("Division of matrix B by A:")
    print(matrix_division)

def question_12():
    """
    Which function in Numpy can be used to swap the byte order of an array?
    """
    print("The function np.ndarray.byteswap() can be used to swap the byte order of an array.")

def question_13():
    """
    What is the significance of the np.linalg.inv function?
    """
    print("The np.linalg.inv function is used to calculate the inverse of a matrix. It is significant in linear algebra and is often used to solve systems of linear equations and for various other mathematical computations.")

def question_14():
    """
    What does the np.reshape function do, and how is it used?
    """
    print("The np.reshape function is used to change the shape of an array without changing its data.")
    print("It allows you to specify the new shape of the array while ensuring that the total number of elements remains constant.")
    print("This function is commonly used in data manipulation and preparation tasks.")

def question_15():
    """
    What is broadcasting in Numpy?
    """
    print("Broadcasting is a mechanism in NumPy that allows arrays with different shapes to be combined in arithmetic operations.")
    print("When operating on arrays of different shapes, NumPy automatically broadcasts the arrays to have compatible shapes so that element-wise operations can be performed.")
    print("This allows for efficient computation without the need for unnecessary duplication of data.")

# Menu-driven program
while True:
    print("\nMenu:")
    print("1. Question 1")
    print("2. Question 2")
    print("3. Question 3")
    print("4. Question 4")
    print("5. Question 5")
    print("6. Question6")
    print("7. Question 7")
    print("8. Question 8")
    print("9. Question 9")
    print("10. Question 10")
    print("11. Question 11")
    print("12. Question 12")
    print("13. Question 13")
    print("14. Question 14")
    print("15. Question 15")
    print("0. Exit")

    choice = input("Enter your choice (0-15): ")

    if choice == '1':
        question_1()
    elif choice == '2':
        question_2()
    elif choice == '3':
        question_3()
    elif choice == '4':
        question_4()
    elif choice == '5':
        question_5()
    elif choice == '6':
        question_6()
    elif choice == '7':
        question_7()
    elif choice == '8':
        question_8()
    elif choice == '9':
        question_9()
    elif choice == '10':
        question_10()
    elif choice == '11':
        question_11()
    elif choice == '12':
        question_12()
    elif choice == '13':
        question_13()
    elif choice == '14':
        question_14()
    elif choice == '15':
        question_15()
    elif choice == '0':
        print("Exiting...")
        break
    else:
        print("Invalid choice! Please enter a number from 0 to 15.")





Menu:
1. Question 1
2. Question 2
3. Question 3
4. Question 4
5. Question 5
6. Question6
7. Question 7
8. Question 8
9. Question 9
10. Question 10
11. Question 11
12. Question 12
13. Question 13
14. Question 14
15. Question 15
0. Exit
Enter your choice (0-15): 11
Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition of matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction of matrix B from matrix A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Menu:
1. Question 1
2. Question 2
3. Question 3
4. Question 4
5. Question 5
6. Question6
7. Question 7
8. Question 8
9. Question 9
10. Question 10
11. Question 11
12. Question 12
13. Question 13
14. Question 14
15. Question 15
0. Exit
Enter your choice (0-15): 1
A Python library is a collection of functions and methods that allow you to perform many actions withou